baseurl = "https://www.webase.tech/"
disableLanguages = ["fr"]
defaultContentLanguage = "cn"
googleAnalytics = ""
summarylength = "20"
theme = "navi-hugo"
title = "日本生活工作学习导航"
[Languages.cn]
contentDir = "content/chinese"
copyright = "Designed & Developed By [Zhengjintao](https://github.com/zhengjintao/)"
languageCode = "zh-cn"
languageName = "中文"
weight = 1
[[Languages.cn.menu.main]]
name = "Home1"
url = "/"
weight = 1
[[Languages.cn.menu.main]]
name = "Products2"
url = "products"
weight = 2
[[Languages.cn.menu.main]]
name = "Blog3"
url = "blog"
weight = 3
[[Languages.cn.menu.main]]
name = "Review4"
pre = "#"
url = "testimonial"
weight = 4
[[Languages.cn.menu.main]]
name = "Contact"
url = "contact"
weight = 5
[Languages.en]
contentDir = "content/english"
copyright = "Designed & Developed By [Zhengjintao](https://github.com/zhengjintao/)"
languageCode = "en-us"
languageName = "En"
weight = 2
[Languages.fr]
contentDir = "content/french"
copyright = "Designed & Developed By [Zhengjintao](https://github.com/zhengjintao/)"
languageCode = "fr-fr"
languageName = "Fr"
weight = 3
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
name = "Blog"
url = "blog"
weight = 1
[[menu.footer]]
name = "Contact"
url = "contact"
weight = 2
[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3
[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[Languages.en.menu.main]]
name = "Products"
url = "products"
weight = 2
[[Languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 3
[[Languages.en.menu.main]]
name = "Review"
pre = "#"
url = "testimonial"
weight = 4
[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5
[params]
author = "zhengjintao"
contact_form_action = "#"
currency = "$"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "100px"
[params.preloader]
enable = true
preloader = ""
[params.subscription]
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
